version: "3.9"

volumes:
  todo_slim_sql:

services:
  front:
    image: sermalenk/skypro-front:lesson-37
    ports:
      - "8080:80"
    depends_on:
      - api
      - database
  database:
    image: postgres
    environment:
      - POSTGRES_DB=todoslim
      - POSTGRES_USER=skypro
      - POSTGRES_PASSWORD=postgres1234
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U skypro -d todoslim" ]
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
#      - ./data/db:/var/lib/postgresql/data
      -  todo_slim_sql:/var/lib/postgresql/data
  api:
    build: .
    volumes:
      - ./env:/project/env/
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    command: ./start_p.sh
