version: "3.9"
   
services:
#  front:
#    image: sermalenk/skypro-front:lesson-34
#    ports:
#      - "8080:80"
#    depends_on:
#      - api
  database:
    image: postgres
    environment:
      - POSTGRES_DB=todoslim
      - POSTGRES_USER=skypro
      - POSTGRES_PASSWORD=postgres1234
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  api:
    build: .
    volumes:
      - ./env:/project/env
#      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - database
#    command: ./run.sh
