# Generated by Django 4.0.5 on 2022-07-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='chat_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
