  name: Build action number one
  on: [push]
  jobs:
    build_and_push:
      runs-on: ubuntu-20.04
      steps:
        - name: clone code
          uses: actions/checkout@v2
        - name: docker build
          run: docker build -t ${{ secrets.DOCKER_USER }}/django-6-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
        - name: docker login
          run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        - name: docker push
          run: docker push ${{ secrets.DOCKER_USER }}/django-6-app:$GITHUB_REF_NAME-$GITHUB_RUN_ID

    deploy:
      runs-on: ubuntu-20.04
      needs: build_and_push
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      steps:
        - name: clone code
          uses: actions/checkout@v2
        - name: render configs
          run: |
            mkdir deploy
            cat docker-compose-server.yaml | envsubst > deploy/docker-compose.yaml
        - name: clone config
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            source: "deploy/docker-compose.yaml"
            target: "django-6-app"
            strip_components: 1
        - name: run docker-compose
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            script: |
              
              cd django-6-app
              echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d
